project_id = "mussjfjktgltgvnvafdu"

[functions.send-invitation]
verify_jwt = false

[functions.test-imap-connection]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = false
