project_id = "mussjfjktgltgvnvafdu"

[functions.send-invitation]
verify_jwt = false

[functions.test-imap-connection]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = false

[functions.n8n-gateway]
verify_jwt = false

[functions.complete-member-registration]
verify_jwt = false

[functions.parse-pdf-fipe]
verify_jwt = false
